version: "3.7"

#    This Source Code Form is subject to the terms of the Mozilla Public License,
#    v. 2.0. If a copy of the MPL was not distributed with this file, You can
#    obtain one at http://mozilla.org/MPL/2.0/. OpenMRS is also distributed under
#    the terms of the Healthcare Disclaimer located at http://openmrs.org/license.
#    
#    Copyright (C) OpenMRS Inc. OpenMRS is a registered trademark and the OpenMRS
#    graphic logo is a trademark of OpenMRS Inc.

services:
    db:
        image: mariadb:10.11.7
        command: "mariadbd --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci"
        environment:
            MARIADB_DATABASE: ${OMRS_DB_NAME:-openmrs}
            MARIADB_USER: ${OMRS_DB_USER:-openmrs}
            MARIADB_PASSWORD: ${OMRS_DB_PASSWORD:-openmrs}
            MARIADB_ROOT_PASSWORD: ${OMRS_DB_ROOT_PASSWORD:-openmrs}
        healthcheck:
            test: "mariadb --user=${OMRS_DB_USER:-openmrs} --password=${OMRS_DB_PASSWORD:-openmrs} --execute \"SHOW DATABASES;\""
            interval: 3s
            timeout: 5s
            retries: 3
        volumes:
            - db-data:/var/lib/mysql

    api:
        image: openmrs/openmrs-core:${TAG:-nightly}
        build:
            context: .
            cache_from:
                - openmrs/openmrs-core:${TAG:-dev}
                - openmrs/openmrs-core:${TAG:-nightly}
        ports:
            - "8080:8080"
            - "9404:9404"
        environment:
            OMRS_DB: ${OMRS_DB:-mariadb}
            OMRS_DB_HOSTNAME: ${OMRS_DB_HOSTNAME:-db}
            OMRS_DB_NAME: ${OMRS_DB_NAME:-openmrs}
           # OMRS_DB_USERNAME: ${OMRS_DB_USERNAME:-openmrs}
            OMRS_DB_USER: ${OMRS_DB_USER:-openmrs}
            OMRS_DB_PASSWORD: ${OMRS_DB_PASSWORD:-openmrs}
            OMRS_ADMIN_USER_PASSWORD: ${OMRS_ADMIN_USER_PASSWORD:-Admin123}
            OMRS_ADMIN_PASSWORD_LOCKED: ${OMRS_ADMIN_PASSWORD_LOCKED:-true}
            OMRS_CREATE_TABLES: "true"
            OMRS_AUTO_UPDATE_DATABASE: "true"
            OMRS_MODULE_WEB_ADMIN: "true"
            OMRS_DEV_DEBUG: "true"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/openmrs"]
            interval: 3s
            timeout: 5s
            retries: 3
        volumes:
            - openmrs-data:/openmrs/data/
            - ./logs:/openmrs/logs 

    prometheus:
        image: prom/prometheus
        container_name: openmrs-prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./monitoring/alert.rules.yml:/etc/prometheus/alert.rules.yml
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--web.enable-remote-write-receiver"
    alertmanager:
        image: prom/alertmanager:v0.27.0
        container_name: openmrs-alertmanager
        ports:
            - "9093:9093"
        volumes:
            - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
        command:
            - "--config.file=/etc/alertmanager/alertmanager.yml"
            - "--storage.path=/alertmanager"
            - "--log.level=info"
    grafana:
        image: grafana/grafana
        container_name: openmrs-grafana
        ports:
        - "3000:3000"
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_USERS_ALLOW_SIGN_UP=false
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
        volumes:
            - ./monitoring/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
            - ./monitoring/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
            - ./monitoring/dashboards:/etc/grafana/provisioning/dashboards/json
        depends_on:
            - prometheus
            - loki

    node-exporter:
        image: prom/node-exporter
        ports:
            - "9100:9100"

    loki:
        image: grafana/loki:2.9.0
        ports:
            - "3100:3100"
        volumes:
            - ./monitoring/loki-config.yaml:/etc/loki/local-config.yaml
        command: -config.file=/etc/loki/local-config.yaml

    promtail:
        image: grafana/promtail:2.9.0
        volumes:
            - ./promtail-config.yml:/etc/promtail/config.yml
            - /var/lib/docker/containers:/var/lib/docker/containers:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        command: -config.file=/etc/promtail/config.yml

    jaeger:
        image: jaegertracing/all-in-one:1.53
        environment:
            - COLLECTOR_OTLP_ENABLED=true
        ports:
            - "16686:16686"
            - "14268:14268"
            - "14250:14250"
            - "4319:4317"
    cadvisor:
        image: gcr.io/cadvisor/cadvisor:latest
        ports:
            - "8081:8080"
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
    otel-collector:
        image: otel/opentelemetry-collector:latest
        command: ["--config=/etc/otel-config.yaml"]
        volumes:
            - ./monitoring/otel-config.yaml:/etc/otel-config.yaml
        ports:
            - "4317:4317"
            - "4318:4318"

         

    otel-app:
        build: ./otel-app
        ports:
            - "3001:3000"
        environment:
            - OTEL_SERVICE_NAME=otel-app
            - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
        depends_on:
            - jaeger
            - api

            

volumes:
    db-data:
    openmrs-data:

    
