sonar.projectKey=horry-oumaima_openmrs-core
sonar.organization=horry-oumaima
sonar.projectName=OpenMRS Core
sonar.projectVersion=3.0.0-SNAPSHOT
sonar.sources=api/src/main/java,web/src/main/java,webapp/src/main/java
sonar.tests=api/src/test/java
sonar.java.binaries=api/target/classes,web/target/classes
sonar.java.test.binaries=api/target/test-classes
sonar.coverage.jacoco.xmlReportPaths=api/target/site/jacoco/jacoco.xml
sonar.java.checkstyle.reportPaths=api/target/checkstyle-result.xml
sonar.exclusions=**/generated/**,**/liquibase/**,**/*.xml
sonar.test.exclusions=**/test/**
sonar.language=java
sonar.sourceEncoding=UTF-8
